version: 2
updates:
  - package-ecosystem: npm
    directory: "/"

    schedule:
      interval: daily

    commit-message:
      prefix: chore
      include: scope

    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

    labels:
      - dependencies

    open-pull-requests-limit: 10

    groups:
      # All sentry packages should be updated together
      sentry:
        patterns:
          - "@sentry/*"
      prisma:
        patterns:
          - "@prisma/client*"
          - "prisma*"

  - package-ecosystem: github-actions
    directory: "/.github/workflows"

    schedule:
      interval: daily

    commit-message:
      prefix: chore
      include: scope

    labels:
      - dependencies

  - package-ecosystem: docker
    directory: "/"

    schedule:
      interval: daily

    commit-message:
      prefix: chore
      include: scope

    labels:
      - dependencies
