version: 2
updates:
  - package-ecosystem: npm
    directory: "/api"

    schedule:
      interval: daily

    commit-message:
      prefix: chore
      include: scope

    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

    labels:
      - dependencies
      - javascript
      - node
