version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/:cached

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - ./data:/data/
    command: redis-server --loglevel verbose

  server:
    restart: always
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./node_modules/.prisma:/usr/src/app/node_modules/.prisma
      - api_node_modules:/usr/src/app/node_modules/
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
    driver: local
  next_node_modules:
    driver: local
  api_node_modules:
    driver: local
