version: "3"

services:
  integration-tests:
    image: postgres
    restart: always
    container_name: integration-tests
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=integration
      - POSTGRES_PASSWORD=integration
    ports:
      - "5433:5432"

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/:cached

  redis:
    restart: always
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    command: redis-server --loglevel warning --requirepass redis
    volumes:
      - ./data:/data/

  api:
    restart: always
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules/.prisma:/usr/src/app/node_modules/.prisma
      - api_node_modules:/usr/src/app/node_modules/
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - redis


volumes:
  postgres_data:
    driver: local
  next_node_modules:
    driver: local
  api_node_modules:
    driver: local
