name: "Destroy Preview"

on:
  pull_request:
    types: [closed]

defaults:
  run:
    working-directory: ./infrastructure

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  terraform:
    name: Clean up Terraform
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Select Terraform Workspace
        id: workspace
        run: terraform workspace select preview-pr-${{ github.event.pull_request.number }}

      - name: Terraform Destroy
        run: terraform apply -auto-approve -destroy -var-file="test.tfvars"

      - name: Destoy Workspace
        run: |
          terraform workspace select default
          terraform workspace delete preview-pr-${{ github.event.pull_request.number }}
